rook: add command rook status
red-hat-storage/odf-cli pull request #27
Opened 2024-02-28 13:09 UTC by subhamkrai

rook: add command rook status
add command rook status for printing rook-ceph CR status.

2024-02-28 19:17 UTC, travisn requested changes
After this is rebased, just a minor suggestion...

2024-02-28 19:17 UTC, travisn commented on cmd/odf/get/rook_status.go
> +	Short:   "Print the phase and/or conditions of every CR in the namespace",
```suggestion
	Short:   "Print the phase and/or conditions of Rook CRs",
```

2024-03-01 09:11 UTC, subhamkrai commented on cmd/odf/get/rook_status.go
> +	Short:   "Print the phase and/or conditions of every CR in the namespace",
done

2024-03-01 16:04 UTC, travisn approved these changes

2024-03-01 16:14 UTC, merged